name: sketchpad
description: A HiveDB sample project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  hive_ce: ^2.20.0
  hive_ce_flutter: ^2.4.0
  path_provider: ^2.1.6

flutter:
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
